apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: customers
  labels:
    app: customers
spec:
  revisionHistoryLimit: 3
  replicas: 5
  selector:
    matchLabels:
      app: customers
  template:
    metadata:
      labels:
        app: customers
    spec:
      containers:
        - image: 6255/customer-info:customers-8d678c0f2b73705fab5bc835666fc9ced2f8c6f0
          imagePullPolicy: Always
          name: svc
          ports:
            - containerPort: 3000
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause:
            duration: 1m
        - setWeight: 40
        - pause:
            duration: 1m
        - setWeight: 60
        - pause:
            duration: 1m
